# Generated by Django 3.1.3 on 2021-06-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_content_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='cate_img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='照片'),
        ),
    ]
