# Generated by Django 3.1.3 on 2021-06-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_categorys_cate_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='cate_img',
            field=models.ImageField(blank=True, default='/static/img/others.png', null=True, upload_to='img', verbose_name='照片'),
        ),
    ]
