# Generated by Django 3.1.3 on 2021-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210604_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='cate_img',
            field=models.ImageField(blank=True, default='/static/img/others.png', null=True, upload_to='upload/file', verbose_name='照片'),
        ),
    ]
